import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:provider/provider.dart';

import '../../../app/routes/app_routes.dart';
import '../../../app/theme/app_colors.dart';
import '../../../app/theme/app_gradients.dart';
import '../../../providers/auth_provider.dart';
import '../../../providers/profile_provider.dart';

class SignupView extends StatefulWidget {
  const SignupView({super.key});

  @override
  State<SignupView> createState() => _SignupViewState();
}

class _SignupViewState extends State<SignupView> {
  final _formKey = GlobalKey<FormState>();

  // ============================================================
  // COMMON FIELDS
  // ============================================================

  final _nameController = TextEditingController();
  final _emailController = TextEditingController();
  final _phoneController = TextEditingController();

  final _passwordController = TextEditingController();
  final _confirmPasswordController = TextEditingController();

  // ============================================================
  // EMPLOYEE FIELDS
  // ============================================================

  final _departmentController = TextEditingController();
  final _designationController = TextEditingController();

  // ============================================================
  // VENDOR FIELDS
  // ============================================================

  final _vendorNameController = TextEditingController();
  final _contactPersonController = TextEditingController();

  // ============================================================
  // PASSWORD VISIBILITY
  // ============================================================

  bool _obscurePassword = true;
  bool _obscureConfirmPassword = true;

  // ============================================================
  // DEFAULT ROLE
  // ============================================================

  String _selectedRole = 'EMPLOYEE';

  // ============================================================
  // DISPOSE
  // ============================================================

  @override
  void dispose() {
    _nameController.dispose();
    _emailController.dispose();
    _phoneController.dispose();

    _passwordController.dispose();
    _confirmPasswordController.dispose();

    _departmentController.dispose();
    _designationController.dispose();

    _vendorNameController.dispose();
    _contactPersonController.dispose();

    super.dispose();
  }

  // ============================================================
  // SIGNUP
  // ============================================================

  Future<void> _signup() async {
    FocusScope.of(context).unfocus();

    if (!_formKey.currentState!.validate()) {
      return;
    }

    final authProvider = context.read<AuthProvider>();
    final profileProvider = context.read<ProfileProvider>();

    final success = await authProvider.signup(
      fullName: _nameController.text.trim(),
      email: _emailController.text.trim(),
      password: _passwordController.text,
      role: _selectedRole,

      // ========================================================
      // EMPLOYEE
      // ========================================================

      // DO NOT send employeeCode.
      //
      // employee_code is generated by the Supabase database
      // trigger/default.
      //
      department: _selectedRole == 'EMPLOYEE'
          ? _departmentController.text.trim()
          : null,

      designation: _selectedRole == 'EMPLOYEE'
          ? _designationController.text.trim()
          : null,

      // ========================================================
      // COMMON
      // ========================================================
      phone: _phoneController.text.trim(),

      vendorName: _selectedRole == 'VENDOR'
          ? _vendorNameController.text.trim()
          : null,

      contactPerson: _selectedRole == 'VENDOR'
          ? _contactPersonController.text.trim()
          : null,
    );

    if (!mounted) {
      return;
    }

    if (success) {
      debugPrint('[Vendor Signup] AUTH/RECORD SETUP SUCCESS');
      final profileLoaded = await profileProvider.loadProfile();

      if (!mounted) {
        return;
      }

      final profile = profileProvider.profile;

      if (!profileLoaded || profile == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              profileProvider.error ?? 'Unable to load your profile.',
            ),
            duration: const Duration(seconds: 5),
          ),
        );
        return;
      }

      if (!profile.isActive) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text(
              'Your account was created but is not active yet. Please contact support.',
            ),
          ),
        );
        return;
      }

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Account created successfully.')),
      );

      final destination = profile.isEmployee
          ? AppRoutes.employeeHome
          : profile.isVendor
          ? AppRoutes.vendorDashboard
          : null;

      if (destination == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Unknown account role: ${profile.role}')),
        );
        return;
      }

      debugPrint('[Vendor Signup] ROLE = ${profile.role}');
      debugPrint('[Vendor Signup] NAVIGATION ROUTE = $destination');
      Navigator.pushReplacementNamed(context, destination);
    } else {
      final message =
          authProvider.errorMessage ?? 'Signup failed. Please try again.';

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(message), duration: const Duration(seconds: 5)),
      );
    }
  }
  // ============================================================
  // INPUT DECORATION
  // ============================================================

  InputDecoration _inputDecoration({
    required String hintText,
    required IconData icon,
    Widget? suffixIcon,
  }) {
    return InputDecoration(
      hintText: hintText,
      prefixIcon: Icon(icon),
      suffixIcon: suffixIcon,
    );
  }

  // ============================================================
  // FIELD LABEL
  // ============================================================

  Widget _fieldLabel(String text) {
    return Text(
      text,
      style: TextStyle(
        fontSize: 14.sp,
        fontWeight: FontWeight.w600,
        color: AppColors.textPrimary,
      ),
    );
  }

  // ============================================================
  // SPACING
  // ============================================================

  Widget _spacing([double value = 18]) {
    return SizedBox(height: value.h);
  }

  // ============================================================
  // BUILD
  // ============================================================

  @override
  Widget build(BuildContext context) {
    final authProvider = context.watch<AuthProvider>();

    return Scaffold(
      body: Container(
        width: double.infinity,
        height: double.infinity,
        decoration: const BoxDecoration(gradient: AppGradients.background),
        child: SafeArea(
          child: SingleChildScrollView(
            keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag,
            padding: EdgeInsets.symmetric(horizontal: 24.w, vertical: 30.h),
            child: Form(
              key: _formKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  SizedBox(height: 20.h),

                  // ==================================================
                  // LOGO
                  // ==================================================
                  Center(
                    child: Container(
                      width: 78.w,
                      height: 78.w,
                      decoration: BoxDecoration(
                        gradient: AppGradients.gold,
                        shape: BoxShape.circle,
                        boxShadow: [
                          BoxShadow(
                            blurRadius: 25.r,
                            spreadRadius: 2.r,
                            color: AppColors.primary.withValues(alpha: 0.25),
                          ),
                        ],
                      ),
                      child: Icon(
                        Icons.restaurant_rounded,
                        size: 42.sp,
                        color: Colors.white,
                      ),
                    ),
                  ),

                  SizedBox(height: 20.h),

                  // ==================================================
                  // TITLE
                  // ==================================================
                  Center(
                    child: Text(
                      'Create Account',
                      style: TextStyle(
                        fontSize: 28.sp,
                        fontWeight: FontWeight.w700,
                        color: AppColors.textPrimary,
                      ),
                    ),
                  ),

                  SizedBox(height: 8.h),

                  Center(
                    child: Text(
                      'Join MealFlow today',
                      style: TextStyle(
                        fontSize: 14.sp,
                        color: AppColors.textSecondary,
                      ),
                    ),
                  ),

                  SizedBox(height: 30.h),

                  // ==================================================
                  // ACCOUNT TYPE
                  // ==================================================
                  _fieldLabel('Account Type'),

                  _spacing(8),

                  Container(
                    padding: EdgeInsets.all(4.r),
                    decoration: BoxDecoration(
                      color: Colors.white.withValues(alpha: 0.55),
                      borderRadius: BorderRadius.circular(16.r),
                      border: Border.all(
                        color: AppColors.primary.withValues(alpha: 0.15),
                      ),
                    ),
                    child: Row(
                      children: [
                        Expanded(
                          child: _roleButton(
                            title: 'Employee',
                            icon: Icons.badge_outlined,
                            role: 'EMPLOYEE',
                          ),
                        ),
                        Expanded(
                          child: _roleButton(
                            title: 'Vendor',
                            icon: Icons.storefront_outlined,
                            role: 'VENDOR',
                          ),
                        ),
                      ],
                    ),
                  ),

                  _spacing(22),

                  // ==================================================
                  // FULL NAME
                  // ==================================================
                  _fieldLabel('Full Name'),

                  _spacing(8),

                  TextFormField(
                    controller: _nameController,
                    textCapitalization: TextCapitalization.words,
                    decoration: _inputDecoration(
                      hintText: 'Enter your full name',
                      icon: Icons.person_outline,
                    ),
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Please enter your name';
                      }

                      if (value.trim().length < 2) {
                        return 'Name is too short';
                      }

                      return null;
                    },
                  ),

                  _spacing(),

                  // ==================================================
                  // EMAIL
                  // ==================================================
                  _fieldLabel('Email'),

                  _spacing(8),

                  TextFormField(
                    controller: _emailController,
                    keyboardType: TextInputType.emailAddress,
                    textInputAction: TextInputAction.next,
                    decoration: _inputDecoration(
                      hintText: 'Enter your email',
                      icon: Icons.email_outlined,
                    ),
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Please enter your email';
                      }

                      final emailRegex = RegExp(r'^[^@\s]+@[^@\s]+\.[^@\s]+$');

                      if (!emailRegex.hasMatch(value.trim())) {
                        return 'Enter a valid email';
                      }

                      return null;
                    },
                  ),

                  _spacing(),

                  // ==================================================
                  // PHONE
                  // ==================================================
                  _fieldLabel('Phone'),

                  _spacing(8),

                  TextFormField(
                    controller: _phoneController,
                    keyboardType: TextInputType.phone,
                    textInputAction: TextInputAction.next,
                    decoration: _inputDecoration(
                      hintText: '03XXXXXXXXX',
                      icon: Icons.phone_outlined,
                    ),
                  ),

                  // ==================================================
                  // EMPLOYEE SECTION
                  // ==================================================
                  if (_selectedRole == 'EMPLOYEE') ...[
                    _spacing(),

                    // Department
                    _fieldLabel('Department'),

                    _spacing(8),

                    TextFormField(
                      controller: _departmentController,
                      textCapitalization: TextCapitalization.words,
                      textInputAction: TextInputAction.next,
                      decoration: _inputDecoration(
                        hintText: 'e.g. IT',
                        icon: Icons.business_outlined,
                      ),
                    ),

                    _spacing(),

                    // Designation
                    _fieldLabel('Designation'),

                    _spacing(8),

                    TextFormField(
                      controller: _designationController,
                      textCapitalization: TextCapitalization.words,
                      textInputAction: TextInputAction.next,
                      decoration: _inputDecoration(
                        hintText: 'e.g. Software Engineer',
                        icon: Icons.work_outline,
                      ),
                    ),
                  ],

                  // ==================================================
                  // VENDOR SECTION
                  // ==================================================
                  if (_selectedRole == 'VENDOR') ...[
                    _spacing(),

                    // Vendor Name
                    _fieldLabel('Vendor Name'),

                    _spacing(8),

                    TextFormField(
                      controller: _vendorNameController,
                      textCapitalization: TextCapitalization.words,
                      textInputAction: TextInputAction.next,
                      decoration: _inputDecoration(
                        hintText: 'Enter vendor/company name',
                        icon: Icons.storefront_outlined,
                      ),
                      validator: (value) {
                        if (_selectedRole != 'VENDOR') {
                          return null;
                        }

                        if (value == null || value.trim().isEmpty) {
                          return 'Vendor name is required';
                        }

                        return null;
                      },
                    ),

                    _spacing(),

                    // Contact Person
                    _fieldLabel('Contact Person'),

                    _spacing(8),

                    TextFormField(
                      controller: _contactPersonController,
                      textCapitalization: TextCapitalization.words,
                      textInputAction: TextInputAction.next,
                      decoration: _inputDecoration(
                        hintText: 'Enter contact person name',
                        icon: Icons.person_outline,
                      ),
                    ),
                  ],

                  _spacing(),

                  // ==================================================
                  // PASSWORD
                  // ==================================================
                  _fieldLabel('Password'),

                  _spacing(8),

                  TextFormField(
                    controller: _passwordController,
                    obscureText: _obscurePassword,
                    textInputAction: TextInputAction.next,
                    decoration: _inputDecoration(
                      hintText: 'Create a password',
                      icon: Icons.lock_outline,
                      suffixIcon: IconButton(
                        onPressed: () {
                          setState(() {
                            _obscurePassword = !_obscurePassword;
                          });
                        },
                        icon: Icon(
                          _obscurePassword
                              ? Icons.visibility_outlined
                              : Icons.visibility_off_outlined,
                        ),
                      ),
                    ),
                    validator: (value) {
                      if (value == null || value.length < 6) {
                        return 'Password must be at least 6 characters';
                      }

                      return null;
                    },
                  ),

                  _spacing(),

                  // ==================================================
                  // CONFIRM PASSWORD
                  // ==================================================
                  _fieldLabel('Confirm Password'),

                  _spacing(8),

                  TextFormField(
                    controller: _confirmPasswordController,
                    obscureText: _obscureConfirmPassword,
                    textInputAction: TextInputAction.done,
                    decoration: _inputDecoration(
                      hintText: 'Confirm your password',
                      icon: Icons.lock_reset_outlined,
                      suffixIcon: IconButton(
                        onPressed: () {
                          setState(() {
                            _obscureConfirmPassword = !_obscureConfirmPassword;
                          });
                        },
                        icon: Icon(
                          _obscureConfirmPassword
                              ? Icons.visibility_outlined
                              : Icons.visibility_off_outlined,
                        ),
                      ),
                    ),
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please confirm your password';
                      }

                      if (value != _passwordController.text) {
                        return 'Passwords do not match';
                      }

                      return null;
                    },
                  ),

                  SizedBox(height: 30.h),

                  // ==================================================
                  // CREATE ACCOUNT BUTTON
                  // ==================================================
                  SizedBox(
                    width: double.infinity,
                    height: 54.h,
                    child: DecoratedBox(
                      decoration: BoxDecoration(
                        gradient: AppGradients.gold,
                        borderRadius: BorderRadius.circular(18.r),
                      ),
                      child: ElevatedButton(
                        onPressed: authProvider.isLoading ? null : _signup,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: Colors.transparent,
                          shadowColor: Colors.transparent,
                          disabledBackgroundColor: Colors.transparent,
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(18.r),
                          ),
                        ),
                        child: authProvider.isLoading
                            ? SizedBox(
                                width: 22.w,
                                height: 22.w,
                                child: const CircularProgressIndicator(
                                  strokeWidth: 2,
                                  color: Colors.white,
                                ),
                              )
                            : Text(
                                'Create Account',
                                style: TextStyle(
                                  fontSize: 16.sp,
                                  fontWeight: FontWeight.w600,
                                  color: Colors.white,
                                ),
                              ),
                      ),
                    ),
                  ),

                  SizedBox(height: 20.h),

                  // ==================================================
                  // LOGIN
                  // ==================================================
                  Center(
                    child: TextButton(
                      onPressed: authProvider.isLoading
                          ? null
                          : () {
                              Navigator.pop(context);
                            },
                      child: Text(
                        'Already have an account? Sign In',
                        style: TextStyle(
                          color: AppColors.primary,
                          fontSize: 14.sp,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                  ),

                  SizedBox(height: 20.h),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  // ============================================================
  // ROLE BUTTON
  // ============================================================

  Widget _roleButton({
    required String title,
    required IconData icon,
    required String role,
  }) {
    final isSelected = _selectedRole == role;

    return GestureDetector(
      onTap: () {
        if (_selectedRole == role) {
          return;
        }

        setState(() {
          _selectedRole = role;
        });
      },
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        padding: EdgeInsets.symmetric(vertical: 12.h),
        decoration: BoxDecoration(
          gradient: isSelected ? AppGradients.gold : null,
          borderRadius: BorderRadius.circular(13.r),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              icon,
              size: 20.sp,
              color: isSelected ? Colors.white : AppColors.textSecondary,
            ),
            SizedBox(width: 7.w),
            Text(
              title,
              style: TextStyle(
                fontSize: 14.sp,
                fontWeight: FontWeight.w600,
                color: isSelected ? Colors.white : AppColors.textPrimary,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
